---
- name: download nodenv
  ansible.builtin.git:
    repo: "https://github.com/nodenv/nodenv.git"
    dest: "~/.nodenv"
    update: no

- name: make plugin directory
  ansible.builtin.file:
    path: "~/.nodenv/plugins"
    state: directory
    mode: 0755

- name: download node-build
  ansible.builtin.git:
    repo: "https://github.com/nodenv/node-build.git"
    dest: "~/.nodenv/plugins/node-build"
    update: no

- name: download nodenv-yarn-install
  ansible.builtin.git:
    repo: "https://github.com/pine/nodenv-yarn-install.git"
    dest: "~/.nodenv/plugins/nodenv-yarn-install"
    update: no

- name: check_installed_node
  ansible.builtin.stat:
    path: "~/.nodenv/versions/{{ node_version }}/bin/node"
  register: check_installed_node

- name: install node
  block:
    - name: install node
      ansible.builtin.shell: "arch -x86_64 ~/.nodenv/bin/nodenv install {{ node_version }}"
  when: check_installed_node.stat.exists == false

- name: set node global version
  ansible.builtin.shell: "~/.nodenv/bin/nodenv global {{ node_version }}"

- name: npm package install 
  ansible.builtin.shell: "~/.nodenv/bin/nodenv exec npm install -g {{ item }}"
  with_items:
    - "{{ npm_packages }}"

- name: nodenv rehash
  ansible.builtin.shell: "~/.nodenv/bin/nodenv rehash"

- name: make .claude directory
  ansible.builtin.file:
    path: "~/.claude"
    state: directory
    mode: 0755

- name: copy CLAUDE.md
  ansible.builtin.copy:
    src: "CLAUDE.md"
    dest: "~/.claude/CLAUDE.md"
    mode: 0644

- name: copy settings.json
  ansible.builtin.copy:
    src: "settings.json"
    dest: "~/.claude/settings.json"
    mode: 0644
