---
- name: create docker config directory
  ansible.builtin.file:
    path: "~/.docker"
    state: directory
    mode: "0700"

- name: copy docker config.json
  ansible.builtin.copy:
    src: config.json
    dest: "~/.docker/config.json"
    mode: "0600"
