---
- name: download goenv
  ansible.builtin.git:
    repo: "https://github.com/syndbg/goenv.git"
    dest: "~/.goenv"
    update: no

- name: check installed go
  ansible.builtin.stat:
    path: "~/.goenv/versions/{{ go_version }}/bin/go"
  register: check_installed_go

- name: install go
  block:
    - name: install go
      ansible.builtin.shell: "~/.goenv/bin/goenv install {{ go_version }}"

    - name: goenv rehash
      ansible.builtin.shell: "~/.goenv/bin/goenv rehash"

    - name: set go global version
      ansible.builtin.shell: "~/.goenv/bin/goenv global {{ go_version }}"
  when: check_installed_go.stat.exists == false

- name: go get
  ansible.builtin.shell: "export GOROOT=~/.goenv/versions/{{ go_version }} && export GOPATH=~/go/{{ go_version }} && ~/.goenv/versions/{{ go_version }}/bin/go install {{ item }}"
  with_items:
    - "{{ go_pkg }}"

