# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'rails', '7.0.8'
gem 'rubocop', '1.56.3'
gem 'rubocop-ast', '1.29.0'
gem 'rubocop-github', '0.20.0'
gem 'rubocop-performance', '1.19.1'
gem 'rubocop-rails', '2.21.1'
gem 'solargraph', '0.49.0'
