---
- name: tap manaflow-ai/cmux
  community.general.homebrew_tap:
    name: manaflow-ai/cmux
    state: present
  when: ansible_distribution == 'MacOSX'

- name: install cmux
  community.general.homebrew_cask:
    name: cmux
    state: present
  when: ansible_distribution == 'MacOSX'
