---
- name: download rbenv
  ansible.builtin.git:
    repo: "https://github.com/rbenv/rbenv.git"
    dest: "~/.rbenv"
    update: no

- name: make plugin directory
  ansible.builtin.file:
    path: "~/.rbenv/plugins"
    state: directory
    mode: 0755

- name: download ruby-build
  ansible.builtin.git:
    repo: "https://github.com/rbenv/ruby-build.git"
    dest: "~/.rbenv/plugins/ruby-build"
    update: no

- name: check_installed_ruby
  ansible.builtin.stat:
    path: "~/.rbenv/versions/{{ ruby_version }}/bin/ruby"
  register: check_installed_ruby

- name: install ruby
  block:
    - name: install ruby
      ansible.builtin.shell: "~/.rbenv/bin/rbenv install {{ ruby_version }}"

    - name: set ruby global version
      ansible.builtin.shell: "~/.rbenv/bin/rbenv global {{ ruby_version }}"
  when: check_installed_ruby.stat.exists == false

- name: gem install 
  ansible.builtin.shell: "~/.rbenv/bin/rbenv exec gem install {{ item }}"
  with_items:
    - "{{ gem_pkg }}"

- name: rbenv rehash
  ansible.builtin.shell: "~/.rbenv/bin/rbenv rehash"

- name: make bundle directory
  ansible.builtin.file:
    path: "~/.bundle"
    state: directory
    mode: 0755

- name: copy bundler config
  ansible.builtin.copy:
    src: "config"
    dest: "~/.bundle/config"
    mode: 0644

