---
- name: download rbenv
  ansible.builtin.git:
    repo: "https://github.com/rbenv/rbenv.git"
    dest: "~/.rbenv"
    update: no

- name: make plugin directory
  ansible.builtin.file:
    path: "~/.rbenv/plugins"
    state: directory
    mode: 0755

- name: download ruby-build
  ansible.builtin.git:
    repo: "https://github.com/rbenv/ruby-build.git"
    dest: "~/.rbenv/plugins/ruby-build"
    update: no

- name: check_installed_ruby
  ansible.builtin.stat:
    path: "~/.rbenv/versions/{{ ruby_version }}/bin/ruby"
  register: check_installed_ruby

- name: install ruby
  block:
    - name: install ruby
      ansible.builtin.shell: "RUBY_CFLAGS=\"-w -DUSE_FFI_CLOSURE_ALLOC\" ~/.rbenv/bin/rbenv install {{ ruby_version }}"

    - name: set ruby global version
      ansible.builtin.shell: "~/.rbenv/bin/rbenv global {{ ruby_version }}"
  when: check_installed_ruby.stat.exists == false

- name: copy Gemfile
  ansible.builtin.copy:
    src: "Gemfile"
    dest: "~/.rbenv/versions/{{ ruby_version }}/Gemfile"
    mode: 0644

- name: copy Gemfile.lock
  ansible.builtin.copy:
    src: "Gemfile.lock"
    dest: "~/.rbenv/versions/{{ ruby_version }}/Gemfile.lock"
    mode: 0644

- name: bundle install
  ansible.builtin.shell: "~/.rbenv/bin/rbenv exec bundle install"
  args:
    chdir: "~/.rbenv/versions/{{ ruby_version }}"

- name: rbenv rehash
  ansible.builtin.shell: "~/.rbenv/bin/rbenv rehash"

- name: make bundle directory
  ansible.builtin.file:
    path: "~/.bundle"
    state: directory
    mode: 0755
