# Set to true to use lowercase keywords instead of uppercase.
lowercaseKeywords: false
connections:
  - alias: postgres
    driver: postgresql
    proto: tcp
    user: postgres
    passwd: ""
    host: 127.0.0.1
    port: 5432
    dbName: postgres
    params:
      sslmode: disable

