---
ollama_models:
  - gemma4

aider_bin_path: "{{ ansible_env.HOME }}/.local/bin/aider"
aider_model: "ollama_chat/gemma4"
aider_ollama_api_base: "http://127.0.0.1:11434"
aider_num_ctx: 32768
aider_auto_commits: true
aider_dark_mode: true
aider_yes_always: true
aider_gitignore: true
aider_analytics: false
aider_check_update: false
